import type { InnerQuestion, InnerTest } from "./types.ts";

const q = (
  id: string,
  stem: string,
  correct: string,
  distractors: string[],
  explain: string,
  tags: InnerQuestion["tags"],
  glossarySlug?: string,
): InnerQuestion => ({
  id,
  stem,
  correct,
  distractors,
  explain,
  tags,
  glossarySlug,
});

export const welcomeBasicBank: InnerQuestion[] = [
  q(
    "wb-ai-01",
    "When writing code is no longer the bottleneck, what usually slows teams first?",
    "Unclear goals, fuzzy edges, and no shared picture of done.",
    [
      "How many programming languages the team already uses in production.",
      "The price of GPUs and how often you call the largest model.",
      "How many standups you add to keep everyone in the loop.",
      "Whether the product logo uses a gradient on the home page.",
      "Which Git host you picked for the company repositories.",
      "How long variable names are in the generated TypeScript.",
    ],
    "Code is cheap to generate. Unclear intent is what you pay for later.",
    ["ai-first"],
    "ambiguity",
  ),
  q(
    "wb-ai-02",
    "What is vibe coding on this site?",
    "Prompting by feel with no written contract. Fine for toys. Costly on real systems.",
    [
      "Writing automated tests before any production code, like classic TDD.",
      "Running a formal exam with a large question bank and a random sample.",
      "Shipping only after a frozen 200-page PRD that nobody is allowed to edit.",
      "Pairing in an office so two people type every line together.",
      "Measuring success only by story points closed in the last sprint.",
      "Replacing product managers with a chatbot that files tickets.",
    ],
    "Vibe coding can prototype fast. It still hides disagreements until later.",
    ["ai-first"],
    "prompt-engineering",
  ),
  q(
    "wb-ai-03",
    "Why is a longer prompt a weak substitute for a spec?",
    "A prompt is instructions for one run. A spec is a checkable contract for behavior and done.",
    [
      "Prompts cannot include English, so you have to speak in code comments.",
      "Models refuse to read more than one sentence, so extra words are wasted.",
      "Specs are not allowed in open source, so teams should keep them private.",
      "Longer prompts always cost less than short ones, so they replace docs.",
      "Agents cannot read Markdown, so a spec file would never get used.",
      "A Jira ticket already lists every edge case, so a spec is duplicate work.",
    ],
    "Prompting tunes one call. A spec says what must still be true when you ship.",
    ["ai-first"],
    "prompt-engineering",
  ),
  q(
    "wb-ai-04",
    "In an AI-first team, what should you treat as the scarce resource?",
    "Clarity of intent, constraints, and what counts as acceptance.",
    [
      "How many agents you can spawn at once on the same ticket.",
      "How many Slack channels the team created for this project.",
      "Unused cloud credits sitting in the vendor dashboard.",
      "Keyboard shortcuts in the editor that save a few seconds.",
      "How often you switch the site theme during a work week.",
      "How long commit messages are in the pull request history.",
    ],
    "You can generate a lot of code. Clarity is what still runs out.",
    ["ai-first"],
    "outcome-clarity",
  ),
  q(
    "wb-ai-05",
    "What does directing agents mean here, compared with prompting?",
    "You own the outcome and the guards. Agents do more of the how.",
    [
      "You paste stack traces until the model stops making the same error.",
      "You never review generated diffs because the model sounded confident.",
      "You delete tests because the model said the feature already works.",
      "You only speak in system prompts and never write a shared doc.",
      "You hide requirements from the team so agents stay unbiased.",
      "You measure success by how many prompt tokens you spent this week.",
    ],
    "Directing means owning outcomes and checks, not babysitting every instruction.",
    ["ai-first"],
  ),
  q(
    "wb-ai-06",
    "A teammate says the model will figure out the edge cases. What is the SDD-shaped reply?",
    "Name the edges in the spec, or accept they will show up later as bugs.",
    [
      "Raise temperature so the model gets more creative about the edges.",
      "Ban all AI tools until the feature is already in production.",
      "Replace the spec with a mood board and a few screenshots.",
      "Ship on Friday and write the spec on Monday if users complain.",
      "Load a larger context window instead of writing the edges down.",
      "Rename the ticket to handle edges and leave the description empty.",
    ],
    "If it is not written, two people (or two agents) will not share the same edges.",
    ["ai-first"],
    "specification",
  ),
  q(
    "wb-ai-07",
    "Which statement matches this site’s view of AI in delivery?",
    "AI speeds up the middle of the work. Humans still own vision, guards, and done.",
    [
      "Agents remove the need to write down product intent at all.",
      "Generated code is always the source of truth, even when it drifts.",
      "Quality is whoever merged last, as long as CI is green.",
      "Specs become optional once the team has Copilot or an agent.",
      "Humans should only write YAML configs and never name outcomes.",
      "Validation is the model’s job, so people should not review the result.",
    ],
    "Control moves upstream. You still decide if the output matches intent.",
    ["ai-first"],
  ),
  q(
    "wb-ai-08",
    "What often goes wrong in AI-first work when there is no spec?",
    "Fluent, confident output that still misses real done and the scary edges.",
    [
      "The compiler refuses to run on any file the model touched.",
      "Git cannot store Markdown, so the spec would never live in the repo.",
      "Browsers cannot open localhost, so you cannot demo the slice.",
      "DNS stops resolving for the whole company until you rewrite the spec.",
      "TypeScript becomes illegal in repos that use generated code.",
      "The logo file exceeds 1 KB and the pipeline refuses to ship.",
    ],
    "It looks like progress until you check acceptance. Then the gaps show.",
    ["ai-first"],
    "hallucination-rate",
  ),
  q(
    "wb-ai-09",
    "When is a thin prompt enough?",
    "Toys, spikes, and throwaway exploration, where a wrong edge is cheap.",
    [
      "Payments, auth, and anything you will maintain for the next year.",
      "Any work that touches money, personal data, or security.",
      "Always. Specs are bureaucracy and they only slow a small team.",
      "Only after the feature is already in production and users complain.",
      "Whenever the ticket title is short enough to fit in Slack.",
      "If the CEO asked in a hallway and you want to look fast.",
    ],
    "Prototypes can vibe. Money, security, and long-lived systems want a spec.",
    ["ai-first"],
  ),
  q(
    "wb-ai-10",
    "What should fast mean in an AI-era slice?",
    "A number and a check you can demo, not a vibe in standup.",
    [
      "Whoever typed the most tokens into the agent today.",
      "Shipping before anyone on the team has time to review.",
      "Skipping tests because the model is new and usually good.",
      "A green Jira column with no check you can actually run.",
      "A thumbs-up in chat with no written artifact of done.",
      "Using the fastest model, even when cost and quality get worse.",
    ],
    "Give fast a number. Give big a cap. Then you can demo done.",
    ["ai-first"],
    "success-metrics",
  ),
  q(
    "wb-ai-11",
    "Why keep humans in the loop when agents write most of the diff?",
    "Vision, out-of-bounds, and whether the result matches intent stay human.",
    [
      "Models cannot output TypeScript, so a person must rewrite every file.",
      "Git requires a human name by physics, even when the agent did the work.",
      "Agents cannot read URLs, so someone has to paste the docs by hand.",
      "Humans must click every autocomplete suggestion or the code is invalid.",
      "CI cannot run on generated code, so only people can test the slice.",
      "Open source forbids AI-authored files, so a human has to retype them.",
    ],
    "Agents can do the middle. You still own the edges of the workflow.",
    ["ai-first"],
    "ownership",
  ),
  q(
    "wb-ai-12",
    "What is a healthy use of agents on a well-specified slice?",
    "They work inside the guards. You still review against acceptance.",
    [
      "They invent product scope the spec left silent, then you ship it.",
      "They ignore the spec if the model prefers a different API shape.",
      "They treat the first generated UI as the brand with no design check.",
      "They skip listing out-of-scope items because the model will know.",
      "They hide the spec from reviewers so the PR stays short.",
      "They merge without running the checks you named in the spec.",
    ],
    "Agents are leverage inside a contract. They are not the contract.",
    ["ai-first"],
    "constraints-and-guards",
  ),
  q(
    "wb-sdd-01",
    "On this site, what is spec-driven development mainly about?",
    "Written specs (scope, behavior, acceptance) drive delivery before or beside the code.",
    [
      "Generating as much code as possible from a single prompt and hoping it fits.",
      "Replacing product managers with a chatbot that files Jira tickets.",
      "Writing tests only after production is live and users file bugs.",
      "Using Jira status as the only source of truth for what shipped.",
      "Freezing a 200-page PRD that never updates when you learn something new.",
      "Measuring success only by lines of code added in the last week.",
    ],
    "The spec is the contract teams and agents build against.",
    ["sdd"],
    "spec-driven-development",
  ),
  q(
    "wb-sdd-02",
    "What should a strong spec for one slice usually be?",
    "Short enough to read in one sitting, clear enough two people ship the same behavior, concrete enough to demo done.",
    [
      "As long as the company legal contract, so nothing can be missing.",
      "A single emoji in the ticket title, because the team already knows.",
      "Only a Figma file with no words, so engineering can infer behavior.",
      "A recording of standup, because that is where the real decisions live.",
      "The changelog from last quarter, reused as the spec for this slice.",
      "A list of programming languages, so agents know what they may use.",
    ],
    "Readable, shared, and checkable. Not a contest for the longest doc.",
    ["sdd"],
    "specification",
  ),
  q(
    "wb-sdd-03",
    "How do tickets and specs differ here?",
    "Tickets track and assign work. Specs say what happens and what finished looks like.",
    [
      "Tickets replace specs once you use Jira, so you never need both.",
      "Specs are only for lawyers, so engineers should not have to read them.",
      "A witty ticket title is enough if the team has been together a while.",
      "Specs must live in a different product than tickets or they do not count.",
      "You should pick exactly one and never use both on the same slice.",
      "Agents cannot read tickets, only PDFs, so tickets never carry meaning.",
    ],
    "Use both. A neat backlog of titles is still not a spec.",
    ["sdd"],
  ),
  q(
    "wb-sdd-04",
    "What is a living document in SDD?",
    "A spec that updates as you learn, with a trail of what changed.",
    [
      "A wiki nobody is allowed to edit after the kickoff meeting.",
      "A PDF emailed once at kickoff and then treated as frozen law.",
      "Chat history as the only record of what the team agreed.",
      "A spec you rewrite from scratch every hour with no trail of changes.",
      "Deleting acceptance when a check fails so the doc stays green.",
      "The latest model’s training cut-off date used as the spec version.",
    ],
    "Living does not mean unowned. Someone updates it when reality shifts.",
    ["sdd"],
    "living-document",
  ),
  q(
    "wb-sdd-05",
    "Which order matches the course’s SDD deep dive?",
    "Specify, then plan, then task, then implement.",
    [
      "Implement first, then hope, then write the document after it ships.",
      "Ship first, then spec, then argue about what you meant.",
      "Prompt first, then merge, then spec so the docs match the diff.",
      "Test only after users complain, then write the spec to match.",
      "Design pixels with no written behavior, then let agents fill the gaps.",
      "Standup, then estimate, then ignore edges until they show up in prod.",
    ],
    "Kits like Spec Kit run specify, plan, task, implement.",
    ["sdd"],
  ),
  q(
    "wb-sdd-06",
    "Besides intent, what belongs in a minimal SDD-style slice?",
    "Scope in and out, plus acceptance checks you can actually run.",
    [
      "Only the assignee’s GitHub handle, so people know who to ping.",
      "A list of fonts and a note that the UI should feel premium.",
      "The office Wi-Fi password, so agents can reach internal tools.",
      "A mood line like make it pop, with no numbers or error cases.",
      "Every possible future feature for the next three years in one doc.",
      "The CEO’s favorite editor theme, so generated UI matches taste.",
    ],
    "Name caps, timeouts, and what happens when the file is too large.",
    ["sdd"],
    "acceptance-criteria",
  ),
  q(
    "wb-sdd-07",
    "If generated code and the spec disagree, what should you do?",
    "Resolve it in the open. Change the code or revise the spec. Do not leave silent drift.",
    [
      "Always keep the code. Specs are decorative once a PR exists.",
      "Always keep the spec. Never learn from what production taught you.",
      "Delete both and start a new repo so the conflict goes away.",
      "Ask the model to pick a winner without writing the choice down.",
      "Hide the mismatch from reviewers so the PR stays easy to merge.",
      "Wait for users to file the same bug twice, then pick a side.",
    ],
    "Implementation should satisfy the spec. Drift should be a choice, not an accident.",
    ["sdd"],
    "implementation",
  ),
  q(
    "wb-sdd-08",
    "What is an artifact in this glossary?",
    "A tangible output of the process: specs, diagrams, tickets, tests, repos, release notes.",
    [
      "Only compiled binaries, because those are what customers actually run.",
      "Only marketing slogans, because those are what customers actually read.",
      "Feelings in the retro, because that is where the real learning lives.",
      "The number of agents running overnight on the same ticket.",
      "A private joke in Slack that the team uses as a shorthand for done.",
      "GPU utilization graphs with no link back to what you agreed to build.",
    ],
    "Artifacts are evidence of what was agreed and what shipped.",
    ["sdd"],
    "artifact",
  ),
  q(
    "wb-sdd-09",
    "Why are soft words like secure or fast risky in a spec?",
    "They hide real disagreements until two people ship different behavior.",
    [
      "They make Markdown invalid, so the spec file will not render.",
      "Search engines cannot index them, so the page will not rank.",
      "Models cannot tokenize adjectives, so agents skip those sentences.",
      "They are banned by GitHub, so the PR will fail a status check.",
      "They always mean the same thing on every team, so they waste space.",
      "They slow down TypeScript compile, so the build takes longer.",
    ],
    "Name numbers, errors, and edges. That is how you shrink ambiguity.",
    ["sdd"],
    "ambiguity",
  ),
  q(
    "wb-sdd-10",
    "Where can a spec live and still count?",
    "In a ticket, a wiki, or Markdown in the repo, as long as it says what you are building and how you will know.",
    [
      "Only in a paid requirements tool, otherwise it is not a real spec.",
      "Only in a printed binder, so nobody can change it by accident.",
      "Only inside the model’s weights, because that is where agents look.",
      "Only in a Figma comment thread, because design is the source of truth.",
      "Only if a lawyer signed it, otherwise engineering should ignore it.",
      "Only as a YouTube thumbnail, because video is easier to remember.",
    ],
    "Format is secondary. Shared, checkable behavior is the point.",
    ["sdd"],
    "specification",
  ),
  q(
    "wb-sdd-11",
    "What is a good sign that a spec is working?",
    "Two people answer edge-case questions the same way without booking a room.",
    [
      "The document has the most pages of any wiki article this quarter.",
      "Nobody has opened it since kickoff, which means it must be stable.",
      "The ticket never leaves In progress, so people are still thinking.",
      "Every adjective is world-class, so stakeholders feel confident.",
      "The spec contradicts the acceptance list, which keeps options open.",
      "Only the author understands the nouns, which keeps the design tight.",
    ],
    "Alignment is the test. Length is not.",
    ["sdd"],
  ),
  q(
    "wb-sdd-12",
    "What should you do with work that is out of scope?",
    "Write it down as out, so agents and humans do not silently grow the slice.",
    [
      "Leave it unsaid so people feel empowered to add it if they want.",
      "Put it in a different color with no words, so it stays flexible.",
      "Assume the model will skip it because it was not in the prompt.",
      "Add it as nice to have in the same sitting, with no owner.",
      "Hide it in a footnote nobody reads, then still expect it to ship.",
      "Treat every idea in chat as in-scope until someone objects.",
    ],
    "PDF and scheduled email can wait. They earn their own slices later.",
    ["sdd"],
    "constraints-and-guards",
  ),
  q(
    "wb-sdd-13",
    "How does SDD relate to TDD on this site?",
    "TDD drives design with tests. SDD sets the outcome contract. They can work together.",
    [
      "SDD forbids automated tests, because the spec is already the check.",
      "TDD replaces the need for acceptance criteria on a product slice.",
      "You must pick exactly one forever and never mix them on a team.",
      "TDD is only for hardware, so software teams should ignore it.",
      "SDD means you write tests only after users file bugs in production.",
      "TDD is the same practice as Intent-Driven Engineering, just older.",
    ],
    "TDD is a build and quality habit. SDD is spec as source of truth.",
    ["sdd"],
    "test-driven-development",
  ),
  q(
    "wb-sdd-14",
    "Why write the spec before or beside the first big agent session?",
    "So the session has a source of truth besides chat memory and a ticket title.",
    [
      "Because models cannot generate code unless a spec file exists first.",
      "Because GitHub requires a spec file before it will open a pull request.",
      "Because Vercel will not deploy a preview unless a spec URL is set.",
      "Because search needs a spec URL or the page will not be indexed.",
      "Because TypeScript will not compile unless the spec is in the repo.",
      "Because browsers block unsigned specs, so you must write one first.",
    ],
    "Build against the spec. Do not write it after to match whatever shipped.",
    ["sdd"],
    "spec-driven-development",
  ),
  q(
    "wb-ide-01",
    "In Intent-Driven Engineering on this site, what does IDE stand for?",
    "Intent-Driven Engineering.",
    [
      "Integrated development environment.",
      "Interactive data engine.",
      "Internal delivery estimate.",
      "Instruction-driven execution.",
      "Interface design exploration.",
      "Incremental deployment edition.",
    ],
    "Here IDE is the practice, not the editor acronym.",
    ["ide"],
  ),
  q(
    "wb-ide-02",
    "What is the human’s job in an intent-driven model?",
    "Set the outcome: vision, constraints, and success criteria. Then judge the result.",
    [
      "Type every line the agent would have written, so the repo stays human.",
      "Never set guards, because they only slow agents down on the happy path.",
      "Optimize only for prompt length, because shorter prompts always win.",
      "Treat tickets as the only artifact that matters once work has started.",
      "Hand “done” to the model’s confidence score and skip a human check.",
      "Avoid writing anything that could be checked, so the team stays agile.",
    ],
    "You own vision, guards, and validation. Agents broaden the middle.",
    ["ide"],
    "outcome-clarity",
  ),
  q(
    "wb-ide-03",
    "What is an intent contract, roughly?",
    "You own what must be true. Agents reason how, inside that box.",
    [
      "A legal NDA with Anthropic that you sign before using Claude.",
      "The editor’s license agreement that you accept on first launch.",
      "A promise to never write tests because agents will cover quality.",
      "A sprint velocity target that the team must hit no matter the scope.",
      "A brand color token file that agents must copy into every screen.",
      "A list of banned programming languages that the CI pipeline enforces.",
    ],
    "You own the what. Agents reason about the how.",
    ["ide"],
  ),
  q(
    "wb-ide-04",
    "Where does control move in Intent-Driven Engineering?",
    "Upstream: objectives, tradeoffs, and out-of-bounds. Not every line of code.",
    [
      "Into the model vendor’s terms of service, which become the only spec.",
      "Into whoever has the loudest standup and can override the doc.",
      "Into the CI badge color, because green means the intent was met.",
      "Into the default branch name, which encodes how the team works.",
      "Into the choice of package manager, which decides the architecture.",
      "Away from any written artifact, so the team can stay flexible.",
    ],
    "You specify the edges more, not less.",
    ["ide"],
    "ownership",
  ),
  q(
    "wb-ide-05",
    "Which sequence matches the new developer workflow in the intent article?",
    "Define intent, set guardrails, monitor execution, then verify and ship.",
    [
      "Receive tasks, implement them, then move on to the next ticket.",
      "Prompt, merge, then celebrate because the model sounded sure.",
      "Design pixels, ignore quality, then ship and fix it in production.",
      "Estimate points, ignore outcomes, then repeat the same sprint shape.",
      "Hire more agents, skip review, then hope the evals catch it later.",
      "Write code first, then invent a spec that matches whatever shipped.",
    ],
    "The old model was task execution. The new model is outcome architecture.",
    ["ide"],
  ),
  q(
    "wb-ide-06",
    "How do the four pillars show up in intent-driven work?",
    "Product names the win. Design constrains experience. Build stays in architecture guards. Quality checks original intent.",
    [
      "Only Build matters once agents exist, because they write the code.",
      "Quality is just whether TypeScript compiles, so evals are optional.",
      "Design is optional if the model picked a font that looks modern.",
      "Product is whoever filed the ticket first, so the spec can stay thin.",
      "Pillars are only blog tags. They never change how you run a slice.",
      "You pick one pillar and ignore the others for the life of the product.",
    ],
    "Emphasis moves upstream. Product, Design, Build, and Quality still apply.",
    ["ide"],
  ),
  q(
    "wb-ide-07",
    "What must stay true about validation?",
    "You remain the judge. Does this output match the intent and constraints we agreed?",
    [
      "The model’s self-score is the release gate, so people can skip review.",
      "If it compiles, it matches intent, so acceptance is extra ceremony.",
      "If the demo is pretty, you can skip acceptance and ship the same day.",
      "Users will invent acceptance in production, so you should not write it.",
      "Reviewers should not read the spec, because that would bias the PR.",
      "Evals are only for research labs, not for a product team shipping weekly.",
    ],
    "Tests, evals, and review still exist. More so when AI is in the loop.",
    ["ide"],
    "evaluation-dataset",
  ),
  q(
    "wb-ide-08",
    "What is a guardrail in this sense?",
    "A written or enforced limit: security, data, budget, allowed deps, or never ship without a human on X.",
    [
      "A CSS outline on buttons, so focus states look more premium.",
      "The header’s z-index, so the menu always sits above the hero.",
      "A linter rule you never run, so the repo looks strict in screenshots.",
      "A standup icebreaker, so the team feels aligned before the work starts.",
      "The default Tailwind color, so generated UI matches the brand file.",
      "A joke in AGENTS.md that agents are supposed to treat as a hard rule.",
    ],
    "Guards keep the system inside what the team agreed is acceptable.",
    ["ide"],
    "constraints-and-guards",
  ),
  q(
    "wb-ide-09",
    "How is Intent-Driven Engineering different from prompt engineering here?",
    "Prompt engineering tunes instructions for a model. IDE architects outcomes the whole system must satisfy.",
    [
      "They are two names for the same checklist, used in different blog posts.",
      "IDE is only about choosing an editor, like Cursor versus VS Code.",
      "Prompt engineering includes legal contracts that IDE never has to write.",
      "IDE forbids using prompts at all, because prompts are the old way.",
      "Prompt engineering is only for images, not for software delivery.",
      "IDE means writing longer system prompts until the model stops drifting.",
    ],
    "The next step is not a longer prompt. It is owning intent.",
    ["ide"],
    "prompt-engineering",
  ),
  q(
    "wb-ide-10",
    "Why do roles blend in an intent-driven team?",
    "Delivery shifts from isolated execution to shared ownership of outcomes.",
    [
      "Because job titles are illegal in companies that use coding agents.",
      "Because GitHub has one seat, so only one person can own the spec.",
      "Because agents cannot use more than one tool in a single session.",
      "Because PMs are not allowed to write, so engineers must invent intent.",
      "Because designers cannot read specs, so they work only in Figma.",
      "Because only founders may set constraints, so the rest of the team waits.",
    ],
    "Skill more often means communicating vision across product, design, build, and quality.",
    ["ide"],
    "delegation",
  ),
  q(
    "wb-ide-11",
    "What is the complexity trough idea in the course, in one line?",
    "Beginners feel huge speed with vibe. Pros stall on complex systems without structure.",
    [
      "Only juniors should use specs, because seniors already know the edges.",
      "Seniors should never write acceptance, because that is a PM task.",
      "Complexity always means you need more standups, not a tighter spec.",
      "The trough is a Git merge strategy for long-lived feature branches.",
      "Speed always increases in a straight line as you buy a larger model.",
      "Complex systems should stay unspecified so agents can explore freely.",
    ],
    "Toys feel magical. Production systems punish missing requirements.",
    ["ide"],
  ),
  q(
    "wb-ide-12",
    "What should you still do after agents finish a slice?",
    "Audit against success criteria and intent, then release when the bar is met.",
    [
      "Assume the first pass is production-ready because the model was confident.",
      "Skip QA because the model said the feature is done in the last message.",
      "Delete the spec so it cannot contradict the code that already shipped.",
      "Ship on Friday with no rollback note, then watch metrics on Monday.",
      "Measure only lines added, because that is the easiest throughput number.",
      "Hide the PR from the person who wrote the intent, so review stays unbiased.",
    ],
    "Verify and ship is still a human gate.",
    ["ide"],
    "success-metrics",
  ),
  q(
    "wb-gl-01",
    "How do requirements differ from acceptance criteria here?",
    "Requirements are the broader need and why. Acceptance criteria are specific checks for done.",
    [
      "They are two names for the same sentence, used in different templates.",
      "Acceptance is only for lawyers. Requirements are only for the CI pipeline.",
      "Requirements must be written after the code, so they match what shipped.",
      "Acceptance criteria should stay untestable on purpose, so they stay flexible.",
      "Requirements replace the need for a spec, so you can skip the slice doc.",
      "Acceptance is the ticket title, as long as it mentions the user persona.",
    ],
    "Requirements stay broader. Acceptance turns them into a checklist you can run.",
    ["glossary"],
    "acceptance-criteria",
  ),
  q(
    "wb-gl-02",
    "What is traceability here?",
    "Mapping requirements through specs to tasks, code, and tests so changes stay explainable.",
    [
      "A GPS trail of the laptop, so you know where the work was done.",
      "Git blame as the only document, because it already names an author.",
      "Logging every keystroke, so you can replay how the agent wrote the file.",
      "A watermark on screenshots, so design files stay tied to the ticket.",
      "The model’s citation feature only, which is enough for a production audit.",
      "A spreadsheet of vacation days, so you know who can answer questions.",
    ],
    "It links the what to the how. That helps when AI changes a lot of files.",
    ["glossary"],
    "traceability",
  ),
  q(
    "wb-gl-03",
    "What is a PRD in this glossary?",
    "A product-level doc for goals, users, scope, and metrics. It often pairs with finer technical specs.",
    [
      "A pull request description only, reused as the product agreement.",
      "A Python requirements.txt file that lists libraries the app may import.",
      "A performance review document used to score engineers at the end of a cycle.",
      "The production database replica that holds the live customer records.",
      "A pixel-perfect mock with no words, treated as the full product contract.",
      "The same thing as a unit test, just written in a longer template.",
    ],
    "PRDs sit at product level. You still need slice-level behavior and acceptance.",
    ["glossary"],
    "prd",
  ),
  q(
    "wb-gl-04",
    "What is an MVP here?",
    "The smallest version that validates your hypothesis. SDD helps you choose what belongs.",
    [
      "The version with every requested feature, so nobody feels left out.",
      "Whatever shipped on the first Friday, even if you cannot measure it.",
      "A prototype you never measure, because shipping was the only goal.",
      "The logo and a waitlist only, in every case, no matter the product.",
      "A rewrite of the whole platform, sold as the smallest useful slice.",
      "The most complex architecture you can name, so you will not have to redo it.",
    ],
    "Minimum viable is a product bet. It is not skip the spec.",
    ["glossary"],
    "mvp",
  ),
  q(
    "wb-gl-05",
    "What is a context window?",
    "The max tokens a model can attend to in one pass. It limits how much spec, code, and chat you can load together.",
    [
      "The browser viewport width, which decides how much UI you can show.",
      "How many monitors a developer owns, which decides how much they can see.",
      "The length of the sprint, which decides how much work you can promise.",
      "The size of the Git repository on disk, which agents must load in full.",
      "The number of people in a meeting, which is the team’s real context.",
      "The CSS max-width on the layout, which is the site’s context window.",
    ],
    "Pack the right artifacts so the model stays aligned.",
    ["glossary"],
    "context-window",
  ),
  q(
    "wb-gl-06",
    "What is hallucination rate, as used here?",
    "How often a model produces false, made-up, or unsupported content on a defined task.",
    [
      "How often standups run long, which is a process quality signal.",
      "The error rate of the type checker, which is a build quality signal.",
      "The CSS layout shift score, which is a visual quality signal.",
      "How often people forget the glossary, which is a docs quality signal.",
      "Network packet loss, which is an infrastructure quality signal.",
      "The bounce rate of the marketing site, which is a growth quality signal.",
    ],
    "Track it like other defect rates when AI is in the loop.",
    ["glossary"],
    "hallucination-rate",
  ),
  q(
    "wb-gl-07",
    "What is ownership in the glossary sense?",
    "Who is accountable for a decision, a spec slice, or a boundary when reality shifts.",
    [
      "Whose name is in the Git config, which is enough for a production incident.",
      "Who bought the domain, which is enough for product decisions.",
      "Who has admin on Vercel only, which is enough for spec changes.",
      "Who spoke first in the meeting, which is enough to lock the scope.",
      "Who starred the GitHub repo, which is enough to own the backlog.",
      "Who picked the Tailwind theme, which is enough to own the brand.",
    ],
    "Vague ownership is why progress stalls after a strong kickoff.",
    ["glossary"],
    "ownership",
  ),
  q(
    "wb-gl-08",
    "What is velocity here, and what is it not?",
    "The sustainable rate of valuable, working increments. Not heroics or story-point theater.",
    [
      "How fast you can type prompts, which is the new throughput metric.",
      "The model’s tokens per second, which is the team’s real speed.",
      "Story points as a goal to maximize forever, even when quality drops.",
      "Number of PRs regardless of rework, because merge count looks like progress.",
      "How late the team stays, which proves they are committed to the slice.",
      "How many agents you run overnight, which is the new capacity number.",
    ],
    "Clear specs reduce thrash. Then velocity can mean real throughput.",
    ["glossary"],
    "velocity",
  ),
  q(
    "wb-gl-09",
    "What is outcome clarity?",
    "A shared, written picture of what win means for users and the business.",
    [
      "A dashboard with fifty vanity metrics and no one number you would bet on.",
      "A slogan with no checks, reused as the only definition of success.",
      "Shipping anything this week, because motion is the same as a win.",
      "The number of tickets closed, even if none of them changed user outcomes.",
      "A vibe that the demo felt right, with no written bar for done.",
      "Matching a competitor’s screenshot, even if that is not your user’s job.",
    ],
    "Without it, people solve different problems under the same ticket.",
    ["glossary"],
    "outcome-clarity",
  ),
  q(
    "wb-gl-10",
    "What is a use case here?",
    "A short story of an actor achieving a goal with the system. Pair it with precise acceptance for edges.",
    [
      "A SQL JOIN example that shows how two tables are related.",
      "A CSS utility class that names a layout pattern on the page.",
      "A GitHub issue template only, with no story of the user’s goal.",
      "The same thing as a unit test name, just written in business language.",
      "A marketing persona slide with no flow of what the person actually does.",
      "An RFC that never mentions users, so it stays technical and clean.",
    ],
    "Flows help. Acceptance still names the scary edges.",
    ["glossary"],
    "use-case",
  ),
  q(
    "wb-gl-11",
    "What is a contract at an API or module boundary?",
    "Agreed inputs, outputs, and error behavior. A compact spec for an integration.",
    [
      "A PDF of the employment agreement that new hires sign on day one.",
      "The cloud vendor’s invoice, which is the real contract for the system.",
      "A handshake in the hallway, which is enough if the team is small.",
      "The OpenAPI file you never update, so it drifts from the live API.",
      "CORS set to star treated as documentation of who may call the API.",
      "A Slack emoji reaction that means we agreed, with no written errors.",
    ],
    "Contracts are specs at a boundary. Keep them as honest as the rest of SDD.",
    ["glossary"],
    "contract",
  ),
  q(
    "wb-gl-12",
    "What is an RFC here?",
    "A written proposal for a notable change: context, decision, alternatives, and consequences.",
    [
      "A request for comments that must be a tweet, so it stays short.",
      "A radio-frequency certification you need before shipping hardware.",
      "A rename of the default branch, treated as the whole decision record.",
      "An automated linter fix, because that is a notable change to the repo.",
      "A calendar invite titled quick chat, which replaces a written proposal.",
      "A screenshot of the error, which is enough context for a big change.",
    ],
    "Use an RFC when the change is notable and people need the trail.",
    ["glossary"],
    "rfc",
  ),
  q(
    "wb-gl-13",
    "What is red teaming in this glossary?",
    "Structured adversarial testing. Try to misuse, break, or trick the system before users do.",
    [
      "Wearing red shirts in the office so the quality team is easy to spot.",
      "A sports bracket for sprints, used to rank which squad shipped fastest.",
      "Only penetration tests on the office wifi, with no look at the product.",
      "Firing the QA team, because agents will find the bugs instead.",
      "Letting agents merge without review, which is a form of adversarial test.",
      "A/B testing button colors only, which is enough to call it red teaming.",
    ],
    "Surface safety and quality gaps on purpose, before users find them.",
    ["glossary"],
    "red-teaming",
  ),
  q(
    "wb-gl-14",
    "What is an evaluation dataset in this glossary?",
    "A labeled set of inputs and expected outputs, or rubrics, used to measure model or system behavior.",
    [
      "The production database dump, used as-is with no labels or rubrics.",
      "A folder of random screenshots, with no expected output written down.",
      "The team’s Spotify playlist, used as a fun stand-in for test cases.",
      "Unlabeled logs you never read, stored in case you need them later.",
      "The contents of node_modules, treated as a large enough sample.",
      "A single happy-path demo script with no fail cases in the set.",
    ],
    "Evals let you test AI features against acceptance-style expectations.",
    ["glossary"],
    "evaluation-dataset",
  ),
  q(
    "wb-gl-15",
    "What is a bottleneck here?",
    "The step, queue, or resource that limits throughput. Find it before you tune everything else.",
    [
      "The slowest laptop in the office, which is always the real constraint.",
      "The CSS file size only, which is the only number worth optimizing.",
      "How many glossary terms you have, which is what limits shipping speed.",
      "The length of the README, which is what slows new people down.",
      "Whether you use tabs or spaces, which is the real delivery constraint.",
      "The number of blog posts, which is what limits how fast the product learns.",
    ],
    "If you ignore the bottleneck, you optimize the wrong part of the pipeline.",
    ["glossary"],
    "bottleneck",
  ),
  q(
    "wb-gl-16",
    "What is code clarity here?",
    "Code that communicates intent: naming, structure, and boundaries you can trace back to specs.",
    [
      "The fewest lines possible, always, even when names become cryptic.",
      "One-letter variables to save tokens when you paste code into a prompt.",
      "Comments that contradict the spec, so readers get both points of view.",
      "Generated code you never read, because the model already understood it.",
      "A 4,000-line file named utils, because one place is easier to search.",
      "Obfuscation so agents cannot copy it, which is treated as a quality bar.",
    ],
    "Clarity is for teammates, future you, and the next agent session.",
    ["glossary"],
    "code-clarity",
  ),
  q(
    "wb-eco-01",
    "What is GitHub Spec Kit, at a basic level?",
    "GitHub’s spec-first kit for AI coding workflows: specify, plan, task, implement.",
    [
      "A replacement for Git itself, so you no longer need commits or branches.",
      "Microsoft’s cloud database, used to store specs instead of Markdown.",
      "An ISTQB exam provider that certifies teams in spec-driven development.",
      "A Figma plugin only, used to generate screens from a written spec.",
      "A hosting company for videos, used to publish spec walkthroughs.",
      "A glossary of legal terms, used as the spec for every product slice.",
    ],
    "It is a kit that helps you write and run specs with agents.",
    ["ecosystem-lite"],
  ),
  q(
    "wb-eco-02",
    "What is OpenSpec, in one line?",
    "An open spec format and change workflow for agent-driven work, including existing codebases.",
    [
      "A closed source IDE you must buy before you can write any spec.",
      "OpenAI’s only official exam, required before you use Codex in a team.",
      "A CSS framework that styles spec documents in the browser.",
      "A video hosting protocol used to stream spec reviews to the team.",
      "A replacement for HTTPS, used to secure agent traffic on the network.",
      "A password manager that stores spec files instead of credentials.",
    ],
    "Often a fit when you already have a system and need delta specs.",
    ["ecosystem-lite"],
  ),
  q(
    "wb-eco-03",
    "What is Kiro in the ecosystem map?",
    "A spec-oriented AI IDE. Structured artifacts, not only a chat box.",
    [
      "A test runner for ISTQB exams, used to grade multiple-choice sittings.",
      "A generic chat wrapper with no artifacts, just a prompt and a reply.",
      "Amazon’s package registry, used to publish spec packages to teams.",
      "A Markdown linter that only checks heading levels in spec files.",
      "A font family used in spec documents so they look more official.",
      "A CI badge service that turns spec coverage into a green shield.",
    ],
    "Look for structured artifacts, not only a prompt box.",
    ["ecosystem-lite"],
  ),
  q(
    "wb-eco-04",
    "What is AGENTS.md for?",
    "In-repo conventions so coding agents know how this project wants to be worked.",
    [
      "A replacement for the license file, so you can drop LICENSE entirely.",
      "A list of employee emails, so agents know who to spam with questions.",
      "The production env secrets, stored in git so agents can deploy.",
      "A marketing landing page, used as the public face of the repo.",
      "The only allowed editor config, so everyone must use the same theme.",
      "A Kubernetes manifest that describes how agents run in the cluster.",
    ],
    "Repo conventions. Not a second glossary.",
    ["ecosystem-lite"],
  ),
  q(
    "wb-eco-05",
    "What is MCP (Model Context Protocol)?",
    "A shared way for tools and agents to connect to context.",
    [
      "A Microsoft Certified Professional exam that covers Azure AI basics.",
      "A CSS layout mode, like flex or grid, used in spec-driven UIs.",
      "A Git merge strategy for combining spec branches into main.",
      "A database index type that speeds up lookups on spec tables.",
      "The same thing as a PRD, just renamed for agent-native teams.",
      "A video codec used to compress recordings of spec reviews.",
    ],
    "A standard for how pieces connect. Not a definition of SDD.",
    ["ecosystem-lite"],
  ),
  q(
    "wb-eco-06",
    "How should you treat ecosystem tools versus the glossary?",
    "Glossary defines words. Ecosystem maps tools, approaches, and standards. Tests may mention both.",
    [
      "Ecosystem replaces the glossary, so you can stop linking to terms.",
      "Every tool is officially endorsed by this site, so you should buy them.",
      "You must buy Spec Kit to do SDD, otherwise the method does not count.",
      "MCP is required before you write a spec, or agents will ignore it.",
      "Kiro is the only valid editor for intent, so other IDEs do not count.",
      "Outer vendor exams are hosted on this site, so you should not leave.",
    ],
    "This site is a map plus vocabulary. Not a marketplace or a certificate mill.",
    ["ecosystem-lite"],
  ),
];

export const welcomeBasic: InnerTest = {
  slug: "welcome-basic",
  title: "Welcome: AI-first, SDD, and intent.",
  level: "basic",
  blurb:
    "Core ideas: AI-first development, spec-driven development, Intent-Driven Engineering, and the glossary on this site.",
  topic: "AI-first development, SDD, and Intent-Driven Engineering",
  sampleRatio: 0.5,
  passPercent: 70,
  published: true,
  estimatedMinutes: "about 10 to 15 minutes",
  bank: welcomeBasicBank,
};
