import type { InnerQuestion, InnerTest } from "./types.ts";

const q = (
  id: string,
  stem: string,
  correct: string,
  distractors: string[],
  explain: string,
  tags: InnerQuestion["tags"],
  glossarySlug?: string,
): InnerQuestion => ({
  id,
  stem,
  correct,
  distractors,
  explain,
  tags,
  glossarySlug,
});

export const welcomeBasicBank: InnerQuestion[] = [
  // --- ai-first (12) ---
  q(
    "wb-ai-01",
    "When implementation is no longer the scarce step, what usually limits teams first?",
    "Ambiguity — unclear goals, edges, and what “done” means.",
    [
      "The number of programming languages on the team.",
      "GPU price alone.",
      "How many standups you schedule.",
      "Whether the logo uses a gradient.",
      "Which Git host you picked.",
      "The length of variable names.",
    ],
    "Code is cheap to generate; unclear intent is expensive. Specs exist to shrink ambiguity before rework.",
    ["ai-first"],
    "ambiguity",
  ),
  q(
    "wb-ai-02",
    "What is “vibe coding” in this site’s vocabulary?",
    "Informal prompting by feel — fast on toys, costly on complex systems.",
    [
      "Writing automated tests before any production code.",
      "A formal ISTQB exam style.",
      "Shipping only after a frozen 200-page PRD.",
      "Pairing only in a physical office.",
      "Measuring success solely by story points.",
      "Replacing product managers with a chatbot.",
    ],
    "Vibe coding is prompting without a written contract. It can prototype quickly and still hide disagreements.",
    ["ai-first"],
    "prompt-engineering",
  ),
  q(
    "wb-ai-03",
    "Why is “just write a longer prompt” a weak substitute for a spec?",
    "A prompt is instructions for one run; a spec is a checkable contract for behavior and done.",
    [
      "Prompts cannot contain English words.",
      "Models refuse to read more than one sentence.",
      "Specs are illegal in open source.",
      "Longer prompts always cost less than short ones.",
      "Agents cannot read Markdown files.",
      "Tickets already encode every edge case.",
    ],
    "Prompt engineering tunes a model call. Specs say what must be true when the work is done, across people and tools.",
    ["ai-first"],
    "prompt-engineering",
  ),
  q(
    "wb-ai-04",
    "In an AI-first team, what should you treat as the scarce resource?",
    "Clarity of intent, constraints, and acceptance.",
    [
      "How many agents you can spawn at once.",
      "The number of Slack channels.",
      "Unused cloud credits only.",
      "Keyboard shortcuts in the editor.",
      "How often you change the theme.",
      "Commit message length.",
    ],
    "The course pitch: infinite code, scarce clarity. Write the outcome before you scale generation.",
    ["ai-first"],
    "outcome-clarity",
  ),
  q(
    "wb-ai-05",
    "What does “directing” agents mean here, as opposed to prompting?",
    "You own the what (intent and guards); agents reason more of the how.",
    [
      "You paste stack traces until the model stops.",
      "You never review generated diffs.",
      "You delete all tests because models are confident.",
      "You only speak in system prompts, never in docs.",
      "You hide requirements from the team.",
      "You measure success by prompt token count.",
    ],
    "Intent-driven work moves you from babysitting instructions to owning outcomes and validation.",
    ["ai-first"],
  ),
  q(
    "wb-ai-06",
    "A teammate says “the model will figure out the edge cases.” What is the SDD-shaped reply?",
    "Name the edges in the spec (or accept they will be invented later as bugs).",
    [
      "Increase temperature so the model is more creative.",
      "Ban all AI tools until the feature ships.",
      "Replace the spec with a mood board.",
      "Ship Friday and write the spec on Monday.",
      "Use a larger context window instead of writing anything.",
      "Rename the ticket to “handle edges”.",
    ],
    "If it is not written, two agents (or two humans) will not share the same “obvious” edges.",
    ["ai-first"],
    "specification",
  ),
  q(
    "wb-ai-07",
    "Which statement matches this site’s view of AI in delivery?",
    "AI accelerates the middle of the workflow; humans still own vision, guards, and “is this done?”",
    [
      "Agents remove the need for product intent.",
      "Generated code is always the source of truth.",
      "Quality is whoever merged last.",
      "Specs are optional once you have Copilot.",
      "Humans should only write YAML, never outcomes.",
      "Validation is the model’s job alone.",
    ],
    "Control moves upstream. You still judge whether output matches intent.",
    ["ai-first"],
  ),
  q(
    "wb-ai-08",
    "What is a typical failure mode of AI-first work without specs?",
    "Confident, fluent output that still misses the real “done” and the scary edges.",
    [
      "The compiler refuses to run.",
      "Git cannot store Markdown.",
      "Browsers cannot open localhost.",
      "DNS stops resolving for the whole company.",
      "TypeScript becomes illegal.",
      "The logo file exceeds 1 KB.",
    ],
    "Hallucination and silent scope gaps look like progress until you check acceptance.",
    ["ai-first"],
    "hallucination-rate",
  ),
  q(
    "wb-ai-09",
    "When is a thin prompt enough?",
    "Toys, spikes, and throwaway exploration where wrong edges are cheap.",
    [
      "Payments, auth, and anything you will maintain for a year.",
      "Any work that touches money or security.",
      "Always — specs are bureaucracy.",
      "Only after the feature is in production.",
      "Whenever the ticket title is short.",
      "If the CEO asked in a hallway.",
    ],
    "Course framing: money/security and long-lived systems want SDD; prototypes may vibe.",
    ["ai-first"],
  ),
  q(
    "wb-ai-10",
    "What should “fast” mean in an AI-era slice?",
    "A number and a check you can demo — not a vibe in the standup.",
    [
      "Whoever types the most tokens today.",
      "Shipping before anyone can review.",
      "Skipping tests because the model is new.",
      "A green Jira column.",
      "A thumbs-up in chat with no artifact.",
      "Using the fastest model regardless of cost.",
    ],
    "The export example in the SDD article: fast has a number; big has a cap.",
    ["ai-first"],
    "success-metrics",
  ),
  q(
    "wb-ai-11",
    "Why keep humans in the loop when agents write most of the diff?",
    "Accountability for vision, out-of-bounds, and whether the result matches intent stays human.",
    [
      "Models cannot output TypeScript.",
      "Git requires a human name by physics.",
      "Agents cannot read URLs.",
      "Humans must click every autocomplete.",
      "CI cannot run on generated code.",
      "Open source forbids AI-authored files.",
    ],
    "Intent-driven engineering: you own the edges of the workflow even when the middle is automated.",
    ["ai-first"],
    "ownership",
  ),
  q(
    "wb-ai-12",
    "What is a healthy use of agents on a well-specified slice?",
    "Execute within guardrails; you still review against acceptance.",
    [
      "Invent product scope the spec left silent and ship it.",
      "Ignore the spec if the model prefers another API.",
      "Treat the first generated UI as the brand.",
      "Skip listing out-of-scope items.",
      "Hide the spec from reviewers.",
      "Merge without running the checks you named.",
    ],
    "Agents are leverage inside a contract, not a replacement for the contract.",
    ["ai-first"],
    "constraints-and-guards",
  ),

  // --- sdd (14) ---
  q(
    "wb-sdd-01",
    "In this site’s vocabulary, what is spec-driven development primarily about?",
    "Written specs (scope, behavior, acceptance) drive delivery before or beside implementation.",
    [
      "Generating as much code as possible from a single prompt.",
      "Replacing product managers with a chatbot.",
      "Writing tests only after production is live.",
      "Using Jira status as the only source of truth.",
      "Freezing a 200-page PRD that never updates.",
      "Measuring success only by lines of code.",
    ],
    "SDD treats the specification as the contract teams and agents build against.",
    ["sdd"],
    "spec-driven-development",
  ),
  q(
    "wb-sdd-02",
    "What should a strong spec for one slice usually be?",
    "Short enough to read in one sitting, clear enough two people would ship the same behavior, concrete enough to demo done.",
    [
      "As long as the legal contract for the company.",
      "A single emoji in the ticket title.",
      "Only a Figma file with no words.",
      "A recording of the standup.",
      "The changelog from last quarter.",
      "A list of programming languages.",
    ],
    "From the “what is SDD” article: readable, shared, and checkable — not the longest doc contest.",
    ["sdd"],
    "specification",
  ),
  q(
    "wb-sdd-03",
    "How do tickets and specs differ here?",
    "Tickets track and assign work; specs say what happens and what finished looks like.",
    [
      "Tickets replace specs once you use Jira.",
      "Specs are only for lawyers.",
      "A ticket title is enough if it is witty.",
      "Specs must live in a different product than tickets.",
      "You should pick exactly one and never use both.",
      "Agents cannot read tickets, only PDFs.",
    ],
    "Use both. A neat backlog of titles is still not a spec.",
    ["sdd"],
  ),
  q(
    "wb-sdd-04",
    "What is a living document in SDD?",
    "Specs that update as you learn, with a trail of what changed — truth over time, not frozen bureaucracy.",
    [
      "A wiki nobody is allowed to edit.",
      "A PDF emailed once at kickoff.",
      "Chat history as the only record.",
      "A spec you rewrite from scratch every hour with no trail.",
      "Deleting acceptance when it fails.",
      "The latest model’s training cut-off date.",
    ],
    "Living does not mean unowned. Someone updates the doc when reality shifts.",
    ["sdd"],
    "living-document",
  ),
  q(
    "wb-sdd-05",
    "Which lifecycle order matches the course’s SDD deep dive?",
    "Specify → plan → task → implement.",
    [
      "Implement → hope → document.",
      "Ship → spec → argue.",
      "Prompt → merge → spec.",
      "Test only after users complain.",
      "Design pixels with no written behavior.",
      "Standup → estimate → ignore edges.",
    ],
    "GitHub Spec Kit and similar kits operationalize specify → plan → task → implement.",
    ["sdd"],
  ),
  q(
    "wb-sdd-06",
    "What belongs in a minimal SDD-style slice besides intent?",
    "Scope in/out and acceptance checks you can actually run.",
    [
      "Only the assignee’s GitHub handle.",
      "A list of fonts.",
      "The office Wi-Fi password.",
      "A mood: “make it pop.”",
      "Every possible future feature for three years.",
      "The CEO’s favorite editor theme.",
    ],
    "The export example names caps, timeouts, and what happens when the file is too large.",
    ["sdd"],
    "acceptance-criteria",
  ),
  q(
    "wb-sdd-07",
    "What is the spec’s job when the generated code and the spec disagree?",
    "Resolve it explicitly: change the code or revise the spec — do not leave a silent drift.",
    [
      "Always keep the code; specs are decorative.",
      "Always keep the spec; never learn from production.",
      "Delete both and start a new repo.",
      "Ask the model to pick without writing it down.",
      "Hide the mismatch from reviewers.",
      "Wait for users to file the same bug twice.",
    ],
    "Glossary: implementation satisfies the spec; drift should be an explicit choice.",
    ["sdd"],
    "implementation",
  ),
  q(
    "wb-sdd-08",
    "What is an artifact in this glossary?",
    "A tangible output of the process: specs, diagrams, tickets, tests, repos, release notes.",
    [
      "Only compiled binaries.",
      "Only marketing slogans.",
      "Feelings in the retro.",
      "The number of agents running.",
      "A private joke in Slack.",
      "GPU utilization graphs alone.",
    ],
    "SDD treats artifacts as evidence of what was agreed and what shipped.",
    ["sdd"],
    "artifact",
  ),
  q(
    "wb-sdd-09",
    "Soft words like “secure” or “fast” in a spec are risky because…",
    "They hide real disagreements until two people ship different behavior.",
    [
      "They make Markdown invalid.",
      "Search engines cannot index them.",
      "Models cannot tokenize adjectives.",
      "They are banned by GitHub.",
      "They always mean the same thing in every team.",
      "They slow down TypeScript compile.",
    ],
    "Name numbers, errors, and edges. That is how SDD shrinks ambiguity.",
    ["sdd"],
    "ambiguity",
  ),
  q(
    "wb-sdd-10",
    "Where can a spec live and still count?",
    "Ticket, wiki, or Markdown in the repo — as long as it answers what you are building and how you will know.",
    [
      "Only in a paid requirements tool.",
      "Only in a printed binder.",
      "Only inside the model’s weights.",
      "Only in a Figma comment thread.",
      "Only if a lawyer signed it.",
      "Only as a YouTube thumbnail.",
    ],
    "Format is secondary. Shared, checkable behavior is the point.",
    ["sdd"],
    "specification",
  ),
  q(
    "wb-sdd-11",
    "What is a good sign that a spec is working?",
    "Two people answer edge-case questions the same way without booking a room.",
    [
      "The document has the most pages on the wiki.",
      "Nobody has opened it since kickoff.",
      "The ticket never leaves “In progress.”",
      "Every adjective is “world-class.”",
      "The spec contradicts the acceptance list.",
      "Only the author understands the nouns.",
    ],
    "Alignment is the test, not document length.",
    ["sdd"],
  ),
  q(
    "wb-sdd-12",
    "What should you do with work that is out of scope?",
    "Write it down as out — so agents and humans do not silently grow the slice.",
    [
      "Leave it unsaid so people feel empowered.",
      "Put it in a different color with no words.",
      "Assume the model will skip it.",
      "Add it to the same sitting as “nice to have” with no owner.",
      "Hide it in a footnote nobody reads and still expect it.",
      "Treat every idea in chat as in-scope.",
    ],
    "The export example: PDF and scheduled email earn their own slices later.",
    ["sdd"],
    "constraints-and-guards",
  ),
  q(
    "wb-sdd-13",
    "How does SDD relate to TDD on this site?",
    "TDD drives design with tests; SDD sets the outcome contract. They complement; they are not the same method.",
    [
      "SDD forbids automated tests.",
      "TDD replaces the need for acceptance criteria.",
      "You must pick exactly one forever.",
      "TDD is only for hardware.",
      "SDD means you write tests after users file bugs.",
      "TDD is the same as Intent-Driven Engineering.",
    ],
    "TDD is a build/quality practice. SDD is the spec-as-source-of-truth habit.",
    ["sdd"],
    "test-driven-development",
  ),
  q(
    "wb-sdd-14",
    "Why write the spec before (or beside) the first big agent session?",
    "So the session has a source of truth besides chat memory and a ticket title.",
    [
      "Because models cannot generate code otherwise.",
      "Because GitHub requires a spec file to open a PR.",
      "Because Vercel will not deploy without one.",
      "Because SEO requires a spec URL.",
      "Because TypeScript will not compile.",
      "Because browsers block unsigned specs.",
    ],
    "The spec is what you build against — not a file you write after to match whatever shipped.",
    ["sdd"],
    "spec-driven-development",
  ),

  // --- ide (12) ---
  q(
    "wb-ide-01",
    "In Intent-Driven Engineering on this site, what does IDE stand for?",
    "Intent-Driven Engineering.",
    [
      "Integrated development environment.",
      "Interactive data engine.",
      "Internal delivery estimate.",
      "Instruction-driven execution.",
      "Interface design exploration.",
      "Incremental deployment edition.",
    ],
    "Here IDE is the practice of owning outcomes and guardrails, not the editor acronym.",
    ["ide"],
  ),
  q(
    "wb-ide-02",
    "What is the human’s job in an intent-driven model?",
    "Architect outcomes: vision, constraints, and success criteria — then judge the result.",
    [
      "Type every line the agent would have written.",
      "Never set guards because they slow agents down.",
      "Optimize only for prompt length.",
      "Treat tickets as the only artifact that matters.",
      "Outsource “done” entirely to the model’s confidence.",
      "Avoid writing anything that could be checked.",
    ],
    "You own vision, guardrails, and validation. Agents broaden the middle.",
    ["ide"],
    "outcome-clarity",
  ),
  q(
    "wb-ide-03",
    "What is an intent contract, roughly?",
    "You own what must be true; agents reason how within that box.",
    [
      "A legal NDA with Anthropic.",
      "The editor’s license agreement.",
      "A promise to never write tests.",
      "A sprint velocity target.",
      "A brand color token file.",
      "A list of banned programming languages.",
    ],
    "Course module 4: intent contracts — you own what; agents reason how.",
    ["ide"],
  ),
  q(
    "wb-ide-04",
    "Where does control move in Intent-Driven Engineering?",
    "Upstream: objectives, tradeoffs, and out-of-bounds — not micromanaging every line.",
    [
      "Into the model vendor’s terms of service only.",
      "Into whoever has the loudest standup.",
      "Into the CI badge color.",
      "Into the default branch name.",
      "Into the choice of package manager.",
      "Away from any written artifact.",
    ],
    "Fear of losing control is natural; in practice you specify the edges more, not less.",
    ["ide"],
    "ownership",
  ),
  q(
    "wb-ide-05",
    "Which sequence matches the “new developer workflow” in the intent article?",
    "Define intent → set guardrails → monitor execution → verify and ship.",
    [
      "Receive tasks → implement → move on.",
      "Prompt → merge → celebrate.",
      "Design pixels → ignore quality → ship.",
      "Estimate points → ignore outcomes → repeat.",
      "Hire more agents → skip review → hope.",
      "Write code → invent the spec to match it.",
    ],
    "The old model was task execution. The new model is outcome architecture.",
    ["ide"],
  ),
  q(
    "wb-ide-06",
    "How do the four pillars show up in intent-driven work?",
    "Product names the win; design constrains experience; build stays in architecture guards; quality checks original intent.",
    [
      "Only Build matters once agents exist.",
      "Quality is just whether TypeScript compiles.",
      "Design is optional if the model picked a font.",
      "Product is whoever filed the ticket first.",
      "Pillars are only blog tags, never workflow.",
      "You pick one pillar and ignore the others forever.",
    ],
    "Emphasis moves upstream, but Product, Design, Build, and Quality still apply.",
    ["ide"],
  ),
  q(
    "wb-ide-07",
    "What must stay true about validation?",
    "You remain the judge: does this output match the intent and constraints we agreed?",
    [
      "The model’s self-score is the release gate.",
      "If it compiles, it matches intent.",
      "If the demo is pretty, skip acceptance.",
      "Users will invent acceptance in production.",
      "Reviewers should not read the spec.",
      "Evals are only for research labs.",
    ],
    "Tests, evals, and review still exist — especially when AI is in the loop.",
    ["ide"],
    "evaluation-dataset",
  ),
  q(
    "wb-ide-08",
    "What is a guardrail in this sense?",
    "A written or enforced limit: security, data, budget, allowed dependencies, “never ship without a human on X.”",
    [
      "A CSS outline on buttons.",
      "The header’s z-index.",
      "A linter rule you never run.",
      "A standup icebreaker.",
      "The default Tailwind color.",
      "A joke in AGENTS.md.",
    ],
    "Glossary: constraints and guards keep the system inside what the team agreed is acceptable.",
    ["ide"],
    "constraints-and-guards",
  ),
  q(
    "wb-ide-09",
    "How is Intent-Driven Engineering different from “prompt engineering” here?",
    "Prompt engineering tunes instructions for a model; IDE architects outcomes the whole system must satisfy.",
    [
      "They are two names for the same checklist.",
      "IDE is only about choosing an editor.",
      "Prompt engineering includes legal contracts.",
      "IDE forbids using prompts at all.",
      "Prompt engineering is only for images.",
      "IDE means writing longer system prompts.",
    ],
    "The blog: the next step is not longer prompts. It is owning intent.",
    ["ide"],
    "prompt-engineering",
  ),
  q(
    "wb-ide-10",
    "Why do roles blend in an intent-driven team?",
    "Delivery shifts from isolated execution to shared ownership of outcomes.",
    [
      "Because job titles are illegal.",
      "Because GitHub has one seat.",
      "Because agents cannot use more than one tool.",
      "Because PMs are not allowed to write.",
      "Because designers cannot read specs.",
      "Because only founders may set constraints.",
    ],
    "Technical skill increasingly means communicating vision across product, design, build, and quality.",
    ["ide"],
    "delegation",
  ),
  q(
    "wb-ide-11",
    "What is the “complexity trough” idea in the course, in one line?",
    "Beginners feel huge speed with vibe; professionals stall on complex systems without structure.",
    [
      "Only juniors should use specs.",
      "Seniors should never write acceptance.",
      "Complexity always means you need more standups.",
      "The trough is a Git merge strategy.",
      "Speed always increases linearly with model size.",
      "Complex systems should stay unspecified.",
    ],
    "U-shaped productivity: toys feel magical; production systems punish missing requirements.",
    ["ide"],
  ),
  q(
    "wb-ide-12",
    "What should you still do after agents “finish” a slice?",
    "Audit against success criteria and intent, then release when the bar is met.",
    [
      "Assume the first pass is production-ready.",
      "Skip QA because the model said it is done.",
      "Delete the spec so it cannot contradict the code.",
      "Ship on Friday with no rollback note.",
      "Measure only lines added.",
      "Hide the PR from the person who wrote the intent.",
    ],
    "Verify and ship is still a human gate in the intent workflow.",
    ["ide"],
    "success-metrics",
  ),

  // --- glossary (16) ---
  q(
    "wb-gl-01",
    "How do requirements differ from acceptance criteria here?",
    "Requirements are broader needs and why; acceptance criteria are specific, verifiable conditions for “done.”",
    [
      "They are two names for the same sentence.",
      "Acceptance is only for lawyers; requirements are for CI.",
      "Requirements must be written after the code.",
      "Acceptance criteria should stay untestable on purpose.",
      "Requirements replace the need for a spec.",
      "Acceptance is the ticket title.",
    ],
    "Requirements stay broader; acceptance turns them into a checklist you can validate.",
    ["glossary"],
    "acceptance-criteria",
  ),
  q(
    "wb-gl-02",
    "What is traceability here?",
    "Mapping requirements through specs to tasks, code, and tests so changes stay explainable.",
    [
      "A GPS trail of the laptop.",
      "Git blame as the only document.",
      "Logging every keystroke.",
      "A watermark on screenshots.",
      "The model’s citation feature only.",
      "A spreadsheet of vacation days.",
    ],
    "Traceability links the what to the how — useful when AI changes a lot of files.",
    ["glossary"],
    "traceability",
  ),
  q(
    "wb-gl-03",
    "What is a PRD in this glossary?",
    "A product-level document describing goals, users, scope, and metrics — often paired with finer technical specs.",
    [
      "A pull request description only.",
      "A Python requirements.txt file.",
      "A performance review document.",
      "The production database replica.",
      "A pixel-perfect mock with no words.",
      "The same thing as a unit test.",
    ],
    "PRDs sit at product level; SDD still needs slice-level behavior and acceptance.",
    ["glossary"],
    "prd",
  ),
  q(
    "wb-gl-04",
    "What is an MVP here?",
    "The smallest version that validates your hypothesis — SDD helps decide what belongs without silent scope creep.",
    [
      "The version with every requested feature.",
      "Whatever shipped on the first Friday.",
      "A prototype you never measure.",
      "The logo and a waitlist only, always.",
      "A rewrite of the whole platform.",
      "The most complex architecture you can name.",
    ],
    "Minimum viable is a product bet, not “skip the spec.”",
    ["glossary"],
    "mvp",
  ),
  q(
    "wb-gl-05",
    "What is a context window?",
    "The maximum tokens a model can attend to in one pass — it limits how much spec, code, and chat you can load together.",
    [
      "The browser viewport width.",
      "How many monitors a developer owns.",
      "The length of the sprint.",
      "The size of the Git repository on disk.",
      "The number of people in a meeting.",
      "The CSS max-width on the layout.",
    ],
    "Context engineering is packing the right artifacts so the model stays aligned.",
    ["glossary"],
    "context-window",
  ),
  q(
    "wb-gl-06",
    "What is hallucination rate, as used here?",
    "How often a model produces false, fabricated, or unsupported content on a defined task or benchmark.",
    [
      "How often standups run long.",
      "The error rate of the type checker.",
      "CSS layout shift score.",
      "How often people forget the glossary.",
      "Network packet loss.",
      "The bounce rate of the marketing site.",
    ],
    "Teams track it as a quality signal alongside traditional defect rates.",
    ["glossary"],
    "hallucination-rate",
  ),
  q(
    "wb-gl-07",
    "What is ownership in the glossary sense?",
    "Who is accountable for a decision, a spec slice, or a boundary when reality shifts.",
    [
      "Whose name is in the Git config.",
      "Who bought the domain.",
      "Who has admin on Vercel only.",
      "Who spoke first in the meeting.",
      "Who starred the GitHub repo.",
      "Who picked the Tailwind theme.",
    ],
    "Vague ownership is why progress stalls after energetic kickoffs.",
    ["glossary"],
    "ownership",
  ),
  q(
    "wb-gl-08",
    "What is velocity here — and what is it not?",
    "Sustainable rate of valuable, working increments — not heroics or story-point theater.",
    [
      "How fast you can type prompts.",
      "The model’s tokens per second.",
      "Story points as a goal to maximize forever.",
      "Number of PRs regardless of rework.",
      "How late the team stays.",
      "How many agents you run overnight.",
    ],
    "Clear specs reduce thrash so velocity reflects real throughput.",
    ["glossary"],
    "velocity",
  ),
  q(
    "wb-gl-09",
    "What is outcome clarity?",
    "A shared, written picture of what “win” means for users and the business.",
    [
      "A dashboard with fifty vanity metrics.",
      "A slogan with no checks.",
      "Shipping anything this week.",
      "The number of tickets closed.",
      "A vibe that the demo “felt right.”",
      "Matching a competitor’s screenshot.",
    ],
    "Without it, design, engineering, and stakeholders solve different problems under one ticket.",
    ["glossary"],
    "outcome-clarity",
  ),
  q(
    "wb-gl-10",
    "What is a use case here?",
    "A narrative of an actor achieving a goal with the system — pair it with precise acceptance for edges.",
    [
      "A SQL JOIN example.",
      "A CSS utility class.",
      "A GitHub issue template only.",
      "The same thing as a unit test name.",
      "A marketing persona slide with no flow.",
      "An RFC that never mentions users.",
    ],
    "Flows help; acceptance still names the scary edges.",
    ["glossary"],
    "use-case",
  ),
  q(
    "wb-gl-11",
    "What is a contract at an API or module boundary?",
    "Agreed inputs, outputs, and error behavior — a compact spec for integrations.",
    [
      "A PDF of the employment agreement.",
      "The cloud vendor’s invoice.",
      "A handshake in the hallway.",
      "The OpenAPI file you never update.",
      "CORS set to * as documentation.",
      "A Slack emoji reaction.",
    ],
    "Contracts are specs at a boundary. Keep them as honest as the rest of SDD.",
    ["glossary"],
    "contract",
  ),
  q(
    "wb-gl-12",
    "What is an RFC here?",
    "A written proposal for a notable change: context, decision, alternatives, and consequences.",
    [
      "A request for comments that must be a tweet.",
      "A radio-frequency certification.",
      "A rename of the default branch.",
      "An automated linter fix.",
      "A calendar invite titled “quick chat.”",
      "A screenshot of the error.",
    ],
    "RFCs are common in open source and larger orgs when the change is notable.",
    ["glossary"],
    "rfc",
  ),
  q(
    "wb-gl-13",
    "What is red teaming in this glossary?",
    "Structured adversarial testing: try to misuse, break, or trick the system before users do.",
    [
      "Wearing red shirts in the office.",
      "A sports bracket for sprints.",
      "Only penetration tests on the wifi.",
      "Firing the QA team.",
      "Letting agents merge without review.",
      "A/B testing button colors only.",
    ],
    "Quality pillar: surface safety and quality gaps on purpose.",
    ["glossary"],
    "red-teaming",
  ),
  q(
    "wb-gl-14",
    "What is an evaluation dataset in this glossary?",
    "A labeled set of inputs and expected outputs (or rubrics) used to measure model or system behavior.",
    [
      "The production database dump.",
      "A folder of random screenshots.",
      "The team’s Spotify playlist.",
      "Unlabeled logs you never read.",
      "The contents of node_modules.",
      "A single happy-path demo script with no fails.",
    ],
    "Evals are how you test AI features against acceptance-style expectations.",
    ["glossary"],
    "evaluation-dataset",
  ),
  q(
    "wb-gl-15",
    "What is a bottleneck here?",
    "The step, queue, or resource that limits throughput — find it before you tune everything else.",
    [
      "The slowest laptop in the office, always.",
      "The CSS file size only.",
      "How many glossary terms you have.",
      "The length of the README.",
      "Whether you use tabs or spaces.",
      "The number of blog posts.",
    ],
    "Specs that ignore bottlenecks optimize the wrong part of the pipeline.",
    ["glossary"],
    "bottleneck",
  ),
  q(
    "wb-gl-16",
    "What is code clarity here?",
    "Code that communicates intent: naming, structure, and boundaries you can trace back to specs.",
    [
      "The fewest lines possible, always.",
      "One-letter variables to save tokens.",
      "Comments that contradict the spec.",
      "Generated code you never read.",
      "A 4,000-line file named utils.",
      "Obfuscation so agents cannot copy it.",
    ],
    "Clarity is for teammates and future you — and for the next agent session.",
    ["glossary"],
    "code-clarity",
  ),

  // --- ecosystem-lite (6) ---
  q(
    "wb-eco-01",
    "What is GitHub Spec Kit, at a basic level?",
    "GitHub’s spec-first kit for AI coding workflows (specify → plan → task → implement).",
    [
      "A replacement for Git itself.",
      "Microsoft’s cloud database.",
      "An ISTQB exam provider.",
      "A Figma plugin only.",
      "A hosting company for videos.",
      "A glossary of legal terms.",
    ],
    "Ecosystem: a product/kit that helps write and execute specs with agents.",
    ["ecosystem-lite"],
  ),
  q(
    "wb-eco-02",
    "What is OpenSpec, in one line?",
    "An open spec format and change workflow for agent-driven work, including existing codebases.",
    [
      "A closed source IDE you must buy.",
      "OpenAI’s only official exam.",
      "A CSS framework.",
      "A video hosting protocol.",
      "A replacement for HTTPS.",
      "A password manager.",
    ],
    "Course: OpenSpec is often cited for brownfield / existing systems.",
    ["ecosystem-lite"],
  ),
  q(
    "wb-eco-03",
    "What is Kiro in the ecosystem map?",
    "A spec-oriented AI IDE — structured artifacts, not only chat.",
    [
      "A test runner for ISTQB.",
      "A generic chat wrapper with no artifacts.",
      "Amazon’s package registry.",
      "A Markdown linter.",
      "A font family.",
      "A CI badge service.",
    ],
    "Ecosystem Tools: structured artifacts, not only a prompt box.",
    ["ecosystem-lite"],
  ),
  q(
    "wb-eco-04",
    "What is AGENTS.md for?",
    "In-repo conventions so coding agents know how this project wants to be worked.",
    [
      "A replacement for the license file.",
      "A list of employee emails.",
      "The production env secrets.",
      "A marketing landing page.",
      "The only allowed editor config.",
      "A Kubernetes manifest.",
    ],
    "Standards on /ecosystem: conventions in the repo, not a second glossary.",
    ["ecosystem-lite"],
  ),
  q(
    "wb-eco-05",
    "What is MCP (Model Context Protocol)?",
    "A shared way for tools and agents to connect to context.",
    [
      "A Microsoft Certified Professional exam.",
      "A CSS layout mode.",
      "A Git merge strategy.",
      "A database index type.",
      "The same thing as a PRD.",
      "A video codec.",
    ],
    "Ecosystem Standards: how pieces fit together — not a definition of SDD.",
    ["ecosystem-lite"],
  ),
  q(
    "wb-eco-06",
    "How should you treat ecosystem tools vs the glossary?",
    "Glossary defines words; ecosystem maps tools, approaches, and standards. Tests may mention both.",
    [
      "Ecosystem replaces the glossary.",
      "Every tool is officially endorsed by this site.",
      "You must buy Spec Kit to do SDD.",
      "MCP is required before you write a spec.",
      "Kiro is the only valid editor for intent.",
      "Outer vendor exams are hosted on this site.",
    ],
    "This site is a map plus vocabulary — not a marketplace or a certificate mill.",
    ["ecosystem-lite"],
  ),
];

export const welcomeBasic: InnerTest = {
  slug: "welcome-basic",
  title: "Basic welcome: AI-first, SDD, and intent",
  level: "basic",
  blurb:
    "Core ideas: AI-first development, spec-driven development, Intent-Driven Engineering, and the glossary you will see on this site.",
  topic: "AI-first development, SDD, and Intent-Driven Engineering",
  sampleRatio: 0.5,
  passPercent: 70,
  published: true,
  estimatedMinutes: "about 15–20 minutes",
  bank: welcomeBasicBank,
};
